// <auto-generated />
using System;
using Cozinha_BE.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grupo2A.Migrations
{
    [DbContext(typeof(CozinhaContext))]
    [Migration("20241102220906_AddDescricaoTipoPratoColumn")]
    partial class AddDescricaoTipoPratoColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Cozinha_BE.Model.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PratoIdPrato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdIngrediente");

                    b.HasIndex("PratoIdPrato");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Prato", b =>
                {
                    b.Property<long>("IdPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Receita")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPratoIdTipoPrato")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoRefeicaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPrato");

                    b.HasIndex("TipoPratoIdTipoPrato");

                    b.HasIndex("TipoRefeicaoId");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Refeicao", b =>
                {
                    b.Property<long>("IdRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<long>("PratoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduzida")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TipoRefeicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoRefeicaoId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRefeicao");

                    b.HasIndex("PratoId");

                    b.HasIndex("TipoRefeicaoId1");

                    b.ToTable("Refeicoes");
                });

            modelBuilder.Entity("Cozinha_BE.Model.TipoDePrato", b =>
                {
                    b.Property<int>("IdTipoPrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoTipoPrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoPrato");

                    b.ToTable("TiposDePrato");
                });

            modelBuilder.Entity("Cozinha_BE.Model.TipoDeRefeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposDeRefeicao");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Ingrediente", b =>
                {
                    b.HasOne("Cozinha_BE.Model.Prato", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("PratoIdPrato");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Prato", b =>
                {
                    b.HasOne("Cozinha_BE.Model.TipoDePrato", "TipoPrato")
                        .WithMany()
                        .HasForeignKey("TipoPratoIdTipoPrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cozinha_BE.Model.TipoDeRefeicao", "TipoRefeicao")
                        .WithMany()
                        .HasForeignKey("TipoRefeicaoId");

                    b.Navigation("TipoPrato");

                    b.Navigation("TipoRefeicao");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Refeicao", b =>
                {
                    b.HasOne("Cozinha_BE.Model.Prato", "Prato")
                        .WithMany()
                        .HasForeignKey("PratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cozinha_BE.Model.TipoDeRefeicao", "TipoRefeicao")
                        .WithMany()
                        .HasForeignKey("TipoRefeicaoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prato");

                    b.Navigation("TipoRefeicao");
                });

            modelBuilder.Entity("Cozinha_BE.Model.Prato", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
